/*
 * This source file was generated by the Gradle 'init' task
 */
package bronson_mod_8_csd402;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

classWendyArrayListTestTestt {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
